language: generic
sudo: required
services:
  - docker

before_install:
  - docker build -t binyammesfin/docker_react -f Dockerfile.dev .

script:
  - docker run binyammesfin/docker_react npm run test -- --coverage
